config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  resources :blog_posts, path: "cric-news"
  get :my_blogs, to: "blog_posts#my_blogs"
  resources :tags, only: [ :show ], param: :slug
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "blog_posts#index"
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
  has_many :blog_posts, dependent: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged

  has_rich_text :body
  has_one_attached :banner_image
  belongs_to :admin
  has_and_belongs_to_many :tags
  validates :title, presence: true, length: { maximum: 255 }
  validates :body, presence: true
end

app/models/tag.rb
class Tag < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged
  validates :name, presence: true, uniqueness: { case_sensitive: false }
  validates :slug, uniqueness: true

  has_and_belongs_to_many :blog_posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ActiveStorage::SetCurrent
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  protected
    def authorize_admin!
      redirect_to root_path, alert: "You don't have permission to view this page" if !current_admin
    end
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  before_action :set_blog_post, only: %i[ show edit update destroy ]
  before_action :authorize_admin!, except: %i[ show index ]
  before_action :authorize_owner!, only: %i[edit update destroy]
  # GET /blog_posts or /blog_posts.json
  def index
    if params[:tag].present?
      @tag = Tag.find_by(slug: params[:tag])
      @blog_posts = @tag.present? ? @tag.blog_posts.order(created_at: :desc) : BlogPost.none
    else
      @blog_posts = BlogPost.all.order(created_at: :desc)
    end
    @tags = Tag.all # Get all the tags for the filter
  end

  # GET /blog_posts/1 or /blog_posts/1.json
  def show
  end

  # GET /blog_posts/new
  def new
    @blog_post = BlogPost.new
  end

  # GET /blog_posts/1/edit
  def edit
  end

  def my_blogs
    @tags = Tag.all
    @blog_posts = current_admin.blog_posts.order(created_at: :desc)
    render :index
  end

  # POST /blog_posts or /blog_posts.json
  def create
    @blog_post = current_admin.blog_posts.new(blog_post_params)  # Assign admin automatically

    if params[:blog_post][:new_tag].present?
      tag = Tag.find_or_create_by(name: params[:blog_post][:new_tag])
      @blog_post.tags << tag unless @blog_post.tags.include?(tag)  # Avoid duplicates
      params[:blog_post][:tag_ids] = @blog_post.tags.map(&:id)  # Ensure tag_ids are passed
    end


    respond_to do |format|
      if @blog_post.save
        format.html { redirect_to @blog_post, notice: "Blog post was successfully created." }
        format.json { render :show, status: :created, location: @blog_post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @blog_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blog_posts/1 or /blog_posts/1.json
  def update
    # Handle new tags if provided
    if params[:blog_post][:new_tag].present?
      tag = Tag.find_or_create_by(name: params[:blog_post][:new_tag])
      @blog_post.tags << tag unless @blog_post.tags.include?(tag)
      params[:blog_post][:tag_ids] = @blog_post.tags.map(&:id)
    end
    respond_to do |format|
      if @blog_post.update(blog_post_params)
        format.html { redirect_to @blog_post, notice: "Blog post was successfully updated." }
        format.json { render :show, status: :ok, location: @blog_post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @blog_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blog_posts/1 or /blog_posts/1.json
  def destroy
    @blog_post.destroy!

    respond_to do |format|
      format.html { redirect_to blog_posts_path, status: :see_other, notice: "Blog post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog_post
      @blog_post = BlogPost.friendly.find(params.expect(:id))
    end

    def authorize_owner!
      unless @blog_post.admin == current_admin
        redirect_to blog_posts_path, alert: "You are not authorized to perform this action."
      end
    end

    # Only allow a list of trusted parameters through.
    def blog_post_params
      params.require(:blog_post).permit(:title, :body, :banner_image, tag_ids: [], new_tag: {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/blog_posts/_blog_post.html.erb
<div class="w-full h-96 rounded-lg bg-gray-200 flex flex-col group">
  <div class="w-full h-64 mb-2">
    <% if blog_post.banner_image.attached? %>
      <%= image_tag blog_post.banner_image, class: "h-full w-full object-cover rounded-t-lg" %>
    <% else %>
      <%= image_tag "books.jpg", class: "h-full w-full object-cover rounded-t-lg" %>
    <% end %>
  </div>

  <div class="h-14 flex-shrink-0 w-full px-4 overflow-hidden text-ellipsis"> 
    <p class="text-xl text-gray-900 overflow-hidden font-semibold"> 
      <%= blog_post.title %>
    </p>
  </div>

  <div class="w-full h-full flex items-center px-4">
    <%= link_to "Read post", blog_post, class: "rounded-md px-3.5 py-2.5 bg-gray-600 hover:underline text-white block font-medium" %>
  </div>
</div>

app/views/blog_posts/_form.html.erb
<%= form_with(model: blog_post, class: "contents") do |form| %>
  <% if blog_post.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(blog_post.errors.count, "error") %> prohibited this blog_post from being saved:</h2>

      <ul class="list-disc ml-6">
        <% blog_post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title, class: ["block shadow-sm rounded-md border outline-hidden px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": blog_post.errors[:title].none?, "border-red-400 focus:outline-red-600": blog_post.errors[:title].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :body %>
    <%= form.rich_textarea :body, class: ["block shadow-sm rounded-md border outline-hidden px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": blog_post.errors[:body].none?, "border-red-400 focus:outline-red-600": blog_post.errors[:body].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :banner_image %>
    <%= form.file_field :banner_image, class: ["block shadow-sm rounded-md border outline-hidden px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": blog_post.errors[:banner_image].none?, "border-red-400 focus:outline-red-600": blog_post.errors[:banner_image].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :tags, "Select or Create Tags" %>
    <div class="grid grid-cols-2 gap-4">
      <% Tag.all.each_with_index do |tag, index| %>
        <!-- Create a 2 column grid with checkboxes -->
        <div class="flex items-center">
          <%= form.check_box :tag_ids, { multiple: true, class: "mr-4" }, tag.id, nil %>
          <%= form.label :tag_ids, tag.name, class: "ml-2" %> 
        </div>
      <% end %>
    </div>

    <div class="my-3">
      <%= form.text_field :new_tag, placeholder: "Add a new tag", class: ["block shadow-sm rounded-md border outline-hidden px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": blog_post.errors[:new_tag].none?, "border-red-400 focus:outline-red-600": blog_post.errors[:new_tag].any?}] %>
    </div>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-md px-3.5 py-2.5 bg-gray-600 hover:bg-gray-800 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/blog_posts/edit.html.erb
<% content_for :title, "Editing blog post" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing blog post</h1>

  <%= render "form", blog_post: @blog_post %>

  <%= link_to "Show this blog post", @blog_post, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:underline inline-block font-medium" %>
  <%= link_to "Back to Home", blog_posts_path, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:underline inline-block font-medium" %>
</div>

app/views/blog_posts/index.html.erb
<% content_for :title, "CricBlog" %>

<div class="w-full">
  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">
      <% if params[:action] == "my_blogs" %>
        My Blogs
      <% else %>
        All Blogs
      <% end %>
    </h1>
  </div>

  <!-- Tag filter section -->
  <div class="mt-6">
    <h2 class="font-normal text-1xl mb-1">Filter by Tags:</h2>
    <div class="flex flex-wrap gap-4">
      <!-- "All" Tag -->
      <% all_selected = params[:tag].blank? %>
      <%= link_to "All", blog_posts_path, class: "px-4 py-2 rounded-md hover:bg-gray-300 #{all_selected ? 'bg-gray-600 text-white' : 'bg-gray-200'}" %>

      <!-- Other Tags -->
      <% @tags.each do |tag| %>
        <% selected = params[:tag].to_s == tag.slug.to_s %>
        <%= link_to tag.name, blog_posts_path(tag: tag.slug), class: "px-4 py-2 rounded-md hover:bg-gray-300 #{selected ? 'bg-gray-600 text-white' : 'bg-gray-200'}" %>
      <% end %>
    </div>
  </div>

  <div id="blog_posts" class="min-w-full grid md:grid-cols-3 lg:grid-cols-4 gap-4 mt-8">
    <%= render @blog_posts %>
  </div>
</div>

app/views/blog_posts/new.html.erb
<% content_for :title, "New blog post" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New blog post</h1>

  <%= render "form", blog_post: @blog_post %>

  <%= link_to "Back to blog posts", blog_posts_path, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:underline inline-block font-medium" %>
</div>

app/views/blog_posts/show.html.erb
<% content_for :title, @blog_post.title %>
<% content_for :head do %>
  <meta property="og:title" content="<%= @blog_post.title %>" />
  <meta property="og:type" content="article" />
  <meta property="og:url" content="<%= request.original_url %>" />

  <meta name="twitter:card" content="summary_large_image" />
  <meta name="twitter:site" content="@blogapp" />
  <meta name="twitter:title" content="<%= @blog_post.title %>" />
<% end %>

<div class="flex flex-col w-full">
  <div class="flex gap-2 mb-4">
    <%= link_to "All Posts", blog_posts_path, class: "px-4 py-2 bg-gray-600 text-white rounded-md hover:underline font-medium inline-block" %>
    <%= link_to ">> #{@blog_post.title}", @blog_post, class: "text-xl text-gray-900 hover:underline mt-1 block" %>
  </div>

  <div class="flex flex-col lg:flex-row mb-4">
    <div class="lg:w-1/2 lg:mr-4 w-full">
      <%= image_tag(@blog_post.banner_image, class: "w-full h-auto max-h-[500px] object-contain") if @blog_post.banner_image.attached? %>
    </div>
  </div>

  <h1 class="font-bold text-4xl mb-2"><%= @blog_post.title %></h1>

  <!-- Display author and publication date below the title -->
  <div class="text-sm text-gray-600 mb-4">
    <span>by <%= @blog_post.admin.email %></span> • 
    <span>Published on <%= @blog_post.created_at.strftime("%a, %b %d, %Y, %I:%M %p") %></span>
  </div>

  <div class="my-2 flex flex-col gap-4">
    <div> <%= @blog_post.body %> </div>
    <!-- Display tags with commas -->
    <% if @blog_post.tags.any? %>
      <div class="mt-2 text-sm text-gray-600">
        Tags:
        <% @blog_post.tags.each do |tag| %>
          <%= link_to tag.name, blog_posts_path(tag: tag.slug), class: "text-gray-600 hover:underline" %>
          <% if tag != @blog_post.tags.last %>, <% end %>
        <% end %>
      </div>
    <% else %>
      <div class="mt-2 text-sm text-gray-600">No tags available</div>
    <% end %>
  </div>

  <!-- Add copyright sign after body -->
  <div class="text-sm text-gray-600 mt-4">
    &copy; CricBlog
  </div>

  <div class="flex items-center gap-4 mt-8">
    <% if current_admin == @blog_post.admin %>
      <!-- Edit and Delete buttons only for blog owner -->
      <%= link_to "Edit blog", edit_blog_post_path(@blog_post), class: "rounded-md px-3.5 py-2.5 bg-gray-100 hover:underline inline-block font-medium" %>
      <%= button_to "Delete blog", @blog_post, method: :delete, data: { turbo_confirm: "Are you sure?" }, class: "rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-800 font-medium" %>
    <% end %>

    <!-- Back to All Blogs Button (Visible to All) -->
    <%= link_to "Back to blog posts", blog_posts_path, class: "rounded-md px-3.5 py-2.5 bg-gray-100 hover:underline inline-block font-medium" %>
  </div>
</div>

app/views/layouts/_admin.html.erb
<span> Logged in as admin <%= current_admin.email %></span>

app/views/layouts/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "CricBlog" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/admin" if current_admin %>
    <%= render "layouts/alerts" %>
    <%= render "shared/header" %> <%# Added the header here %>

    <main class="container mx-auto mt-10 px-5 flex">
      <%= yield %>
    </main>
    <%= render "shared/footer" %> <%# Added the footer here %>
  </body>
</html>

app/views/shared/_footer.html.erb
<footer class="bg-gray-600 text-white py-4 mt-8">
  <div class="container mx-auto text-center">
    <p class="text-lg font-semibold">Contact us: 
      <a href="mailto:anmolt0909@gmail.com">
        anmolt0909@gmail.com
      </a>
    </p>
    <p>&copy; <%= Time.current.year %> CricBlog. All rights reserved.</p>
  </div>
</footer>

app/views/shared/_header.html.erb
<header class="bg-gray-600 text-white py-4">
  <div class="container mx-auto flex justify-between items-center px-4">
    <h1 class="text-2xl font-bold">
      <%= link_to "CricBlog", root_path, class: "text-white" %>
    </h1>
    
    <nav class="flex items-center gap-4">
      <%= link_to "Home", root_path, class: "hover:underline" %>
      <%= link_to "New Post", new_blog_post_path, class: "hover:underline" if current_admin %>
      
      <% if current_admin %>
        <%= button_to 'Logout', destroy_admin_session_path, method: :delete, class: 'px-4 py-2 bg-red-600 text-white rounded-md hover:bg-red-800' %>
      <% else %>
        <%= link_to "Admin Login", new_admin_session_path, class: "px-4 py-2 bg-green-600 text-white rounded-md hover:bg-green-800" %>
      <% end %>
    </nav>
  </div>
</header>